spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/card_system_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      maximum-pool-size: 3
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: "jdbc:postgresql://localhost:5432/card_system_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: true
    ignore-future-migrations: true
    locations: classpath:/migration
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

jwt:
  secret: secret
  expiration: 6000000